cache:
  directories: tmp
language: shell
matrix:
  fast_finish: true
env:
  - NODE=0.10   TYPE=compress
  - NODE=0.10   TYPE=mocha
  - NODE=0.10   TYPE=release/benchmark
  - NODE=0.10   TYPE=release/jetstream
  - NODE=0.12   TYPE=compress
  - NODE=0.12   TYPE=mocha
  - NODE=0.12   TYPE=release/benchmark
  - NODE=0.12   TYPE=release/jetstream
  - NODE=4      TYPE=compress
  - NODE=4      TYPE=mocha
  - NODE=4      TYPE=release/benchmark
  - NODE=4      TYPE=release/jetstream
  - NODE=6      TYPE=compress
  - NODE=6      TYPE=mocha
  - NODE=6      TYPE=release/benchmark
  - NODE=6      TYPE=release/jetstream
  - NODE=8      TYPE=compress
  - NODE=8      TYPE=mocha
  - NODE=8      TYPE=release/benchmark
  - NODE=8      TYPE=release/jetstream
  - NODE=10     TYPE=compress
  - NODE=10     TYPE=mocha
  - NODE=10     TYPE=release/benchmark
  - NODE=10     TYPE=release/jetstream
  - NODE=latest TYPE=compress
  - NODE=latest TYPE=mocha
  - NODE=latest TYPE=release/benchmark
  - NODE=latest TYPE=release/jetstream
before_install:
  - git clone --branch v1.5.2 --depth 1 https://github.com/jasongin/nvs.git ~/.nvs
  - . ~/.nvs/nvs.sh
  - nvs --version
install:
  - nvs add node/$NODE
  - nvs use node/$NODE
  - node --version
  - npm --version --no-update-notifier
  - npm install --no-audit --no-optional --no-save --no-update-notifier
script:
  - node test/$TYPE
