name: ESTree
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  test:
    name: fuzzing
    runs-on: ubuntu-latest
    env:
      NODE: 22
    steps:
      - uses: actions/checkout@v4
      - name: Perform tests
        shell: bash
        run: |
          . ./test/release/install.sh
          node test/mozilla-ast.js 5000
